module.exports = (sequelize, DataTypes) => {
    const Ticket = sequelize.define('Ticket', {
      id: {
        type: DataTypes.STRING(255),
        allowNull: true,
      },
      cod_fluxo: {
        type: DataTypes.INTEGER,
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
      },
      status: DataTypes.STRING(100),
      abertura: DataTypes.STRING(50),
      nome: DataTypes.STRING(255),
      departamento: DataTypes.STRING(150),
      email_solicitante: DataTypes.STRING(150),
      hub: DataTypes.STRING(20),
      unidade: DataTypes.STRING(300),
      criticidade: DataTypes.STRING(30),
      categoria: DataTypes.STRING(100),
      subcategoria: DataTypes.STRING(100),
      assunto: DataTypes.STRING(255),
      descricao: DataTypes.STRING(1000),
      anexo: DataTypes.STRING(600),
      outros_area_negocio: DataTypes.STRING(150),
      novo_usuario: DataTypes.STRING(255),
      usuario_modelo: DataTypes.STRING(255),
      area_negocio: DataTypes.STRING(255),
      centro_custo: DataTypes.STRING(255),
      cpf: DataTypes.INTEGER,
      cargo: DataTypes.STRING(255),
      tipo_usuario: DataTypes.STRING(255),
      telefone: DataTypes.STRING(20),
      empresa_colab_cadastrado: DataTypes.STRING(100),
      matricula: DataTypes.INTEGER,
      sigla_cp: DataTypes.STRING(150),
      registro_cp: DataTypes.STRING(150),
      matricula_senior: DataTypes.INTEGER,
      email_executor: DataTypes.STRING(150),
      aprovador_sap: DataTypes.STRING(150),
      executor: DataTypes.STRING(150),
      cancelado_por: DataTypes.STRING(255),
      finalizado_por: DataTypes.STRING(255),
      resposta_chamado: DataTypes.STRING(1000),
      anexo_resposta: DataTypes.STRING(600),
      data_atual: DataTypes.STRING(150),
      grupo: DataTypes.STRING(150),
      sla: DataTypes.STRING(100),
      st_sla: DataTypes.STRING(100),
      st_sla_corrido: DataTypes.STRING(100),
      ct_tempo_corrido: DataTypes.STRING(20),
    }, {
      tableName: 'tb_tickets',
      timestamps: false,
    });
  
    return Ticket;
  };
  